# Generated by Django 5.2.4 on 2025-08-19 18:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_artile_artiсle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artiсle',
            new_name='Article',
        ),
    ]
