# Generated by Django 5.2.4 on 2025-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_rename_artiсle_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, upload_to='articles/img'),
        ),
    ]
